---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
  #- name: centos-7.1
  #- name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[yum-plugin-versionlock::default]
    attributes:
      yum-plugin-versionlock:
        versions:
          'mc-4.8.13-1.fc22.x86_64': false
          'mc-4.8.13-2.fc22.x86_64': true
